//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucHanhWebTMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BanBe
    {
        public int MaBB { get; set; }
        public string MaKH { get; set; }
        public int MaHH { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public System.DateTime NgayGui { get; set; }
        public string GhiChu { get; set; }
    
        public virtual KhachHang KhachHang { get; set; }
        public virtual HangHoa HangHoa { get; set; }
    }
}
