//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucHanhWebTMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GopY
    {
        public string MaGY { get; set; }
        public int MaCD { get; set; }
        public string NoiDung { get; set; }
        public System.DateTime NgayGY { get; set; }
        public string HoTen { get; set; }
        public string Email { get; set; }
        public string DienThoai { get; set; }
        public bool CanTraLoi { get; set; }
        public string TraLoi { get; set; }
        public Nullable<System.DateTime> NgayTL { get; set; }
    
        public virtual ChuDe ChuDe { get; set; }
    }
}
