//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ThucHanhWebTMDT.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PhanQuyen
    {
        public int MaPQ { get; set; }
        public string MaPB { get; set; }
        public Nullable<int> MaTrang { get; set; }
        public bool Them { get; set; }
        public bool Sua { get; set; }
        public bool Xoa { get; set; }
        public bool Xem { get; set; }
    
        public virtual PhongBan PhongBan { get; set; }
        public virtual TrangWeb TrangWeb { get; set; }
    }
}
